export enum SuccessMessage {
  CREATE = '%s created successfully.',
  FETCH = '%s fetched successfully',
  UPDATE = '%s updated successfully',
  DELETE = '%s deleted successfully',
  REMOVE = '%s removed successfully',
  REGISTER = '%s registered successfully',
  LOGGED_IN = 'logged in successfully',
  STORED = '%s stored successfully',
  PUBLISH = '%s published successfully',
  VERIFY = '%s verified successfully',
  REFRESH = '%s refreshed successfully',
  ARCHIVE = '%s archived successfully',
  PROCESSING = '%s is in processing state.',
}
